### ISSUE TITLE
updated every hour ?

### ISSUE THREAD

**Issue by stayforapple** [maitrungduc1410/webrtc#1]
I want to know if here is the latest edition of Webrtc, thanks.

**Comment by maitrungduc1410** [comment]
this repo is synced with original source twice per day

**Comment by stayforapple** [comment]
Perfect, thank you very much. I have a suggestion, maybe you could change the name of this repo, because  maitrungduc1410 is not good for the search engine. For example, webrtc-synchrony, or so on.
